### PR TITLE
Alejandro Aceituna Cano Challenge

### PR DESCRIPTION
**Pull request by aacecandev**
Hi IGZ Devops Team,

I'm opening this PR to make sure you're aware I'm able to complete the challenge. 

Please, read carefully SOLUTIONS.md, I'm not only resolving problems but proposing improvements.

Kind regards

### CODE REVIEW

**Comment by aacecandev** [comment]
I'm leaving for today, I've worked so far 8 hours in this project today.

It is still in WIP status, but it can give you (and me) a rough idea of what am I able to do in a work journal.

Tomorrow I'm writing you an email to check if I have more time to make a refactor on the dev (python) code and to fix the problems that still happen with the db Dockerfile.

Once I do that, I will be able to check the docker-compose file and to finally deploy into my local kind cluster.

**Comment by aacecandev** [comment]
One more thing, I've take a look to the Git logs and it seems that I've pushed and merged using different identities (aacecan.dev & dev.aacecan)

My apologies about that.

**Comment by jvidal-sysadmin** [comment]
What a awesome job @aacecandev, have you finished yet? :)

**Comment by aacecandev** [comment]
Can I have this evening to make the last commits? I haven't had enough time today.

Last changes, I promise.

**Pull request closed without merging**
